[project]
name = "lse-object-detector"
version = "0.1.0"
description = "LS Electric Object Detector Example"
readme = "README.md"
authors = [
    { name = "Jingeol Ryu", email = "jgryu@ls-electric.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
lse-object-detector = "lse_object_detector:main"

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"
