[project]
name = "ml-object-detector"
version = "0.1.0"
description = "ML Object Detector Example"
readme = "README.md"
authors = [
    { name = "Jingeol Ryu", email = "jgryu@ls-electric.com" }
]
requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "mlflow>=3.4.0",
    "pillow>=12.1.0",
    "ultralytics>=8.4.3",
]

[project.scripts]
ml-object-detector = "ml_object_detector:main"

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"
